
apiVersion: v1
kind: Service
metadata:
  name: kalandula
spec:
  selector:
    app: kalandula
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
    - name : metrics
      port: 5001
      targetPort: 5001
      protocol: TCP

