---
# tasks file for filebeat
- name: Ensure required dependencies are present.
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present
    update_cache: true

- name: Add Elasticsearch apt key.
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    id: 46095ACC8548582C1A2699A9D27D666CD88E42B4
    state: present

- name: Add Filebeat repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/oss-7.x/apt stable main'
    state: present
    update_cache: true
    
# Install Filebeat 

- name: Install Filebeat with apt
  apt:
   name: filebeat
   update_cache: yes

- name: copy configuration
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify: restart filebeat
  

# Enable filebeat
- name: Enable filebeat
  service:
   name: filebeat
   enabled: yes


# Starting Filebeat

- name: Starting Filebeat
  service:
   name: filebeat
   state: started
