plugin: aws_ec2
regions:
  - us-east-1
#filters:
#  tag:Environment: dev
keyed_groups:
  - prefix: tag
    key: tags
compose:
  # set the ansible_host variable to connect with the private IP address without changing the hostname
  ansible_host: private_ip_addresss
hostnames:
  # list in order of hostname precedence; if no var in the list exists for the host do not add the host to inventory
  - private-ip-address