---
- name: copy node_exporter installation
  copy:
    dest: /home/ubuntu/inst_node_exporter.sh
    src: inst_node_exporter.sh
    mode: '0755'

- name: run script
  command: /home/ubuntu/inst_node_exporter.sh

- name: copy node_exporter template
  copy:
    dest: /etc/consul.d/node_exporter.json
    src: node_exporter.json
    mode: '0755'
  notify: restart consul service
